### ISSUE TITLE
Terraform Script not working

### ISSUE THREAD

**Issue by hehacks** [ine-labs/AWSGoat#41]
Hi Team,

I have added my aws access key & secret keys in github actions and tried to deploy AWSGoat with the terraform script. But I am facing the below error. Can someone help me in fixing this issue asap.

![Snip20230529_173](https://github.com/ine-labs/AWSGoat/assets/48447311/1b647152-cf8e-4d4d-bd49-ef66feff7d51)

Thank you :)

**Comment by pandyamarut** [comment]
^^ Facing the same issue. Can someone help.

**Comment by SSKale1** [comment]
Hi @hehacks , we checked the deployment it is working successfully as expected. The error may be caused by some preexisting resources in your AWS Account, the error should be shown in the Terraform Plan step, we can better debug your issue if you share the Terraform Plan step output from the Job output.
