### ISSUE TITLE
Error: `AWS_GOAT_ec2_profile: EntityAlreadyExists`

### ISSUE THREAD

**Issue by za** [ine-labs/AWSGoat#49]
Hi there,

I am getting this when applying the terraform:
```
│ Error: creating IAM instance profile AWS_GOAT_ec2_profile: EntityAlreadyExists: Instance Profile AWS_GOAT_ec2_profile already exists.
│ 	status code: 409, request id: ca6<snipped>
│ 
│   with aws_iam_instance_profile.goat_iam_profile,
│   on main.tf line 3484, in resource "aws_iam_instance_profile" "goat_iam_profile":
│ 3484: resource "aws_iam_instance_profile" "goat_iam_profile" {
│ 
╵
Error: Process completed with exit code 1.
```

I can destroy created resources with `terraform destroy` successfully though. Can someone have a look? Do we have duplicated command somewhere?

**Comment by SSKale1** [comment]
Hi @za , 
We tested the deployments there was no such duplication of resources or error. This may be caused by an alternate installation you may have run which could have left some stray resources. 
These commands should delete the iam instance profile, but also make sure there are no IAM roles with names used in AWSGoat present in your account.

```
aws iam remove-role-from-instance-profile  --instance-profile-name AWS_GOAT_ec2_profile --role-name AWS_GOAT_ROLE
aws iam delete-instance-profile --instance-profile-name AWS_GOAT_ec2_profile
```

**Comment by za** [comment]
Hi @SSKale1 thanks! It fixes my problem.

I wonder, where we can list created iam instance profiles from the aws web console? This is OOT, though.
